-- Kategoriler tablosu
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ürünler tablosu
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  category_id BIGINT REFERENCES categories(id),
  image_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Şubeler tablosu
CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT,
  phone VARCHAR(50),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Siparişler tablosu
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES branches(id),
  total_amount DECIMAL(10, 2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sipariş detayları tablosu
CREATE TABLE IF NOT EXISTS order_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id),
  product_id BIGINT REFERENCES products(id),
  quantity INTEGER NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Örnek kategori verileri
INSERT INTO categories (name, description, is_active) VALUES
('Atıştırmalıklar - Tatlılar', 'Atıştırmalıklar ve tatlı çeşitleri', TRUE),
('Bubble Tea''s', 'Bubble Tea çeşitleri', TRUE),
('Extra', 'Ekstra ürünler', TRUE),
('Fresh Drink''s', 'Taze içecekler', TRUE),
('Hot Coffee and More', 'Sıcak kahve ve diğerleri', TRUE),
('Ice Coffee and More', 'Soğuk kahve ve diğerleri', TRUE),
('Meşrubat', 'Meşrubat çeşitleri', TRUE),
('Tea and More', 'Çay ve diğerleri', TRUE);

-- Örnek ürün verileri
INSERT INTO products (name, price, category_id, is_active) VALUES
('AMERICANO (BÜYÜK)', 55.00, 5, TRUE),
('AMERICANO (KÜÇÜK)', 45.00, 5, TRUE),
('BERRY HIBISCUS(BÜYÜK)', 70.00, 4, TRUE),
('BERRY HIBISCUS(KÜÇÜK)', 60.00, 4, TRUE),
('BİTKİ ÇAYI', 50.00, 8, TRUE),
('BUBBLE TEA(BÜYÜK)', 80.00, 2, TRUE),
('BUBBLE TEA(KÜÇÜK)', 70.00, 2, TRUE),
('BUZLU BARDAK', 15.00, 3, TRUE),
('ÇAY', 15.00, 8, TRUE),
('COLD BREW ( BÜYÜK )', 65.00, 6, TRUE),
('COLD BREW( KÜÇÜK )', 55.00, 6, TRUE),
('COOLIME (BÜYÜK)', 70.00, 4, TRUE),
('COOLIME (KÜÇÜK)', 60.00, 4, TRUE),
('Cornly', 30.00, 1, TRUE),
('DİBEK KAHVE(BÜYÜK)', 50.00, 5, TRUE);

-- Örnek şube verisi
INSERT INTO branches (name, address, phone) VALUES
('Gemlik Şubesi', 'Gemlik Merkez, Bursa', '+90 555 123 4567'),
('Bursa Şubesi', 'Nilüfer, Bursa', '+90 555 987 6543'); 